---

### General project setup

  inferBuildTool: true


stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true

  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10.hana.ondemand.com"
    cfOrg: "633b1128trial"
    cfSpace: "dev"
    cfAppName: "rohit-cap"
    cfCredentialsId: "deploy-to-cf"
    tmsUpload: true

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"

  npmExecuteLint:
    failOnError: true

  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"

  tmsUpload:
    nodeName: "QA"
    credentialsId: "tms-sk"

mavenExecute:
    dockerImage: devxci/mbtci:1.0.14
